# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Disable the Sofle OLED display
CONFIG_ZMK_DISPLAY=n

# Disable RGB / underglow if the board or shield supports it
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Display work queue is not needed when the display is disabled
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=n
